version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nawwa
      - MONGO_INITDB_ROOT_PASSWORD=nawwa123
    volumes:
      - db_data:/data/db

volumes:
  db_data:
